name: Propose a new data item
description: Propose a new data item for the Core dictionary
title: "[New data item]: "
labels: ["enhancement"]
assignees: jamesrhester
body:
        - type: markdown
          attributes:
                  value: "Thank you for taking the time to propose a new data item. Please fill out the following information."
        - type: textarea
          attributes:
                  label: Definition
                  description: |
                    Please define the meaning of the proposed data item, going into as much detail as necessary. Literature references are welcome. 
                  placeholder: "Example: The number of symmetrically-equivalent orientations of the group."
          validations:
                  required: true
        - type: input
          attributes:
                  label: Looping
                  description: Name of the data item that should be tabulated together with the proposed item (if looped) or else write 'top level'. 
                  placeholder: "Example: _atom_site.label"
          validations:
                  required: true
        - type: input
          attributes:
                   label: Data name
                   description: Name of the suggested data item.
                   placeholder: "Example: _atom_site.number_of_groups"
        - type: dropdown
          attributes:
                   label: Type
                   description: Type of the data values.
                   options:
                           - Word (text with no spaces)
                           - Text (arbitrary length text)
                           - Date 
                           - Integer
                           - Real
                           - Complex
                           - Other (explain in the Comments below) 
          validations:
                   required: true
        - type: dropdown
          attributes:
                   label: Compound
                   description: "Indicate whether or not values of this type are single or compound (e.g. matrices)."
                   options:
                           - Single (a single value of type given in Type above)
                           - Array (an array of values of type given in Type above)
                           - Matrix (a 2-dimensional Array)
                           - Other (explain in the Comments below)
        - type: textarea
          attributes: 
                    label: Comments
                    description: "Please comment on any aspect of this proposal."
                    placeholder: "Example: This is needed for high-temperature work."
