name: Propose New Definition
description: Propose a new definition for the Core dictionary
title: "[Definition]: "
labels: ["enhancement"]
assignees: jamesrhester
body:
        - type: markdown
          attributes:
                  value: "Please fill out the following information"
        - type: textarea
          attributes:
                  label: definition
                  description: "Please define the meaning of the proposed data name. You are welcome to use references as necessary"
                  placeholder: "Example: the number of symmetrically-equivalent orientations of the group"
          validations:
                  required: true
        - type: input
          attributes:
                  label: category
                  description: which category does this data name belong to?
                  placeholder: "Example: atom_site"
          validations:
                  required: true
        - type: input
          attributes:
                   label: dataname
                   description: Suggested data name (optional)
                   placeholder: _atom_site.number_of_groups
        - type: dropdown
          attributes:
                   label: type
                   description: type of value
                   options:
                           - Word
                           - Text
                           - Date
                           - Integer
                           - Real
                           - Complex
                           - Other
          validations:
                   required: true
        - type: dropdown
          attributes:
                   label: compound
                   description: Single value/Compound value
                   options:
                           - Single
                           - Array
                           - Matrix
                           - Other
        - type: textarea
          attributes: 
                    label: comments
                    description: "Please comment on any aspect of this proposal"
                    placeholder: "Example: This is needed for high-temperature work"

           
