# Check the syntax, semantics and layout of DDLm dictionaries

name: CIF Syntax and Style Check

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the target repository
        uses: actions/checkout@v6
          
      # Check syntax of all CIF files
      - name: Check CIF syntax
        uses: COMCIFS/cif_syntax_check_action@master
        id: cif_syntax_check

  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    needs: syntax

    steps:
      - name: Check out the target repository
        uses: actions/checkout@v6

      - name: Check out the DDLm reference dictionary
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/DDLm
          path: cif-dictionaries/DDLm

      - name: Check out enumeration templates
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/Enumeration_Templates
          path: cif-dictionaries/Enumeration_Templates

      - name: Check out attribute templates
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/Attribute_Templates
          path: cif-dictionaries/Attribute_Templates

      - name: Run dictionary validity checks
        uses: COMCIFS/dictionary_check_action@main
        id: ddlm_check

  layout:
    name: Layout
    runs-on: ubuntu-latest
    needs: syntax

    steps:
      - name: Get the cache
        uses: actions/cache@v5
        id: cache
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1.10'

      - name: Install Julia packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          julia -e 'import Pkg;Pkg.add("CrystalInfoFramework");Pkg.add("Lerche");Pkg.add("ArgParse")'

      - name: Check out Julia tools
        uses: actions/checkout@v6
        with:
          repository: jamesrhester/julia_cif_tools
          path: julia_cif_tools

      - name: Check out the target repository
        uses: actions/checkout@v6
        with:
          path: cif_core

      - name: Check out the DDLm reference dictionary
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/DDLm
          path: DDLm

      - name: Check out enumeration templates
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/Enumeration_Templates
          path: enum

      - name: Check out attribute templates
        uses: actions/checkout@v6
        with:
          repository: COMCIFS/Attribute_Templates
          path: templ

      - name: Move template files to the expected location
        run: |
          mv enum/templ_enum.cif cif_core/templ_enum.cif
          mv templ/templ_attr.cif cif_core/templ_attr.cif
              
      - name: Run diagnostics
        run: |
          ls -a
          echo "pwd:"
          pwd
          echo "Julia location:"
          which julia
          echo "cif_core contents"
          ls cif_core

      - name: Run dictionary layout checks
        run: |
          julia -e 'using Pkg; Pkg.instantiate(); Pkg.status()'
          for file in cif_core/*.dic
          do
            echo "Checking $file"
            julia -O0 ./julia_cif_tools/linter.jl -i $PWD/cif_core $file $PWD/DDLm/ddl.dic
            if [ $? != 0 ]
            then
              exit 1 ;
            fi
          done
